-   id: sort-property-files
    name: sort property files
    description: sort entries of property files alphabetically
    entry: sort-property-files
    language: python
    files: .*.properties$
    stages: [commit, push, manual]
