-   id: sort-property-files
    name: Sort Property Files
    description: Sort entries of property files alphabetically
    entry: sort-property-files
    language: python
    pass_filenames: true
    files: .*\.properties
